### ISSUE TITLE
Use fixed-point arithmetic for Real

### ISSUE THREAD

**Issue by lbguilherme** [lbguilherme/dronewar#25]
This issue is related to #18.

I propose that Real is implemented using [Fixed-point Arithmetic](http://en.wikipedia.org/wiki/Fixed-point_arithmetic).
## Pros:
- It is faster than floating-point. Can be computed using simple integer operations and do not require the floating-point co-processor. Code is also likely to be better optimized by the compiler as integer arithmetic is better defined and specified.
- It allow us to fix any precision and scale we want. And all calculations will be exact to that precision. Floating-points have dynamic scale, so wired things happen: `2e100 + 1 == 2e100`.
- No problems on equality testing and with NaNs.
## Cons:
- We will have to implement from zero. It is simple, but will need to be well tested to ensure correctness.
- The scale factor is fixed and now there is a well defined maximum value. This means that if we represent length units using the smallest unit of 1nm, it will be impossible to represent the distance of light-years. This will happen:

``` c++
FixedReal dist = 12_ly; // 12 light years = 113528765670969607383416832 * 1nm
// Impossible. this value is just too large for the int precision
// (unless a larger (and slower) int type is used)
// I believe floats are worse:
float distf = 12_ly; // ok
distf += 1_nm; // ok
distf == 12_ly; // true. WHAT?
```

``` c++
FixedReal small = 1_nm;
FixedReal halfsmall = small/2;   //smallest unit is 1nm!!
halfsmall == 0; // true :(
// note: there are ways to fix it with fixed numbers.
```
- We will either have to define a fixed scale factor for everything (possibly bad) or use a different scale factor for each kind of operation and make operation between different scale factors work.

**Comment by Physicist137** [comment]
Finally implemented!!!!!!111!!!!!**!**!**!**
https://github.com/Physicist137/simulator/blob/master/modules/math/number/fixed.hpp
hehe.
